networks:
  todonet:

services:
  postgresdb:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=matthias
      - POSTGRES_DB=mydb
    networks:
      - todonet

  todobackend-springboot:
    image: maeddes/todobackend-springboot:hse24
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgresdb
    networks:
      - todonet

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - todobackend-springboot
    environment:
      - BACKEND_API=http://localhost:8080
    ports:
      - 3000:3000
    networks:
      - todonet