apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todoui
  name: todoui
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: todoui
  type: LoadBalancer
status:
  loadBalancer: {}
